// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/client/aws_lambda.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	lambda "github.com/aws/aws-sdk-go/service/lambda"
	gomock "github.com/golang/mock/gomock"
)

// MockAWSLambdaClient is a mock of AWSLambdaClient interface.
type MockAWSLambdaClient struct {
	ctrl     *gomock.Controller
	recorder *MockAWSLambdaClientMockRecorder
}

// MockAWSLambdaClientMockRecorder is the mock recorder for MockAWSLambdaClient.
type MockAWSLambdaClientMockRecorder struct {
	mock *MockAWSLambdaClient
}

// NewMockAWSLambdaClient creates a new mock instance.
func NewMockAWSLambdaClient(ctrl *gomock.Controller) *MockAWSLambdaClient {
	mock := &MockAWSLambdaClient{ctrl: ctrl}
	mock.recorder = &MockAWSLambdaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSLambdaClient) EXPECT() *MockAWSLambdaClientMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockAWSLambdaClient) Invoke(arg0 *lambda.InvokeInput) (*lambda.InvokeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", arg0)
	ret0, _ := ret[0].(*lambda.InvokeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockAWSLambdaClientMockRecorder) Invoke(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockAWSLambdaClient)(nil).Invoke), arg0)
}
