version: 2.1

workflows:
  version: 2
  deploy:
    jobs:
      - lint:
          context: Twizar
      - test:
          context: Twizar

orbs:
  codecov: codecov/codecov@3.2.0

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:latest-alpine
    steps:
      - checkout
      - run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - run: golangci-lint run -v
  test:
    docker:
      - image: cimg/go:1.17.2
    steps:
      - run: env
      - checkout
      - run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -cover -v ./...
      - codecov/upload
